### ISSUE TITLE
drop 500 server limit (cs:go)

### ISSUE THREAD

**Issue by atomGit** [PredatH0r/SteamServerBrowser#13]
don't know about the other games, but for cs:go there is a 500 cap on the number of servers returned

can that cap be removed?

**Comment by PredatH0r** [comment]
Valve's master server have a bandwidth throtteling implemented which restricts each client IP to receive only 30 UDP packets per minute. One packet can hold 231 IP address, which results in a maximum of 6930 server addresses per minute.
When that limit is reached, the master server won't respond to you for 60secs. You won't be able to send another query, e.g. because you want to specify different server side filters.
So I decided to limit my requests to 500 servers and allow you to run multiple queries in a minute where you can narrow down your server-side search criteria.
I could increase it to 1000, but that won't really solve the problem. Better use server-side filters.

**Comment by atomGit** [comment]
i thought that might be the reason

is the master server queried on startup?  if so (and even if not) i might suggest not doing that and just restoring the old list - i would also suggest adding a 'refresh interval'  option of '0' which means auto-refresh is disabled - example; if you have some favorite servers (and thanks for that BTW) you may not be interested in any others, so no need to refresh/reload

what i'm wondering is, with this cap in place, how do i find servers that are not in the 1st 500?  i'm trying to find all servers with a particular string in the title (like "cmg")

the other question i would have is; how does the Steam/CS server browser get around the packet limit since it seems to have no cap on the number returned?

**Comment by PredatH0r** [comment]
I have some ideas now for the next version:
- function to save the current server list to a file.
- function to load a saved list. When the program starts, it will load the last saved list (if any)
- the file will be a regular text file and can be edited/merged with Notepad
- option for AutoUpdate: Off, Game Server Status, Server List + Status

**Comment by atomGit** [comment]
thanks - i think that will help allot :)

**Comment by PredatH0r** [comment]
in 1.16 you can query up to 6930 servers now (30 packet throttle from steam master * 231 addresses per packet)

A later version may allow to continue pulling servers after a 1min wait period.
The other features mentioned above are also still planned.

**Comment by PredatH0r** [comment]
v2.0 now supports "Custom Server Lists", which can be edited by copy/pasting lines with IP:Port from the clipboard. These lists are restored automatically when the application is restarted.
