### ISSUE TITLE
is steam change the api?

### ISSUE THREAD

**Issue by githubrom** [PredatH0r/SteamServerBrowser#21]
there is now servers show in the app.

**Comment by PredatH0r** [comment]
Since yesterday night's weekly steam maintenance the master server is no longer responding to any requests. It looks like Valve shut down the API. There is no information about this on the documentation page of that API. It's not only affecting my server browser, but also many other applications.

I'm currently looking at alternative APIs, because the main reason of this browser was to NOT use the code built into steam_api.dll to query servers.

**Comment by PredatH0r** [comment]
Fixed in https://github.com/PredatH0r/SteamServerBrowser/releases/tag/v2.35
Also uploaded to Steam Workshop for "Quake Live" and TOXIKK.

**Comment by githubrom** [comment]
thx
