### ISSUE TITLE
Steam web API key

### ISSUE THREAD

**Issue by pizzahut2** [PredatH0r/SteamServerBrowser#33]
I would recommend prompting users to provide their own key, and storing it.

It's great that you included the Steam web API though, please keep it. :)

**Comment by PredatH0r** [comment]
you can paste the key in the "Master server:" field instead of "hl2.master.steampowered.com:27011".

**Comment by pizzahut2** [comment]
@PredatH0r How do you trigger the dialogue which asks whether to go to the Steam website to get an API key? I saw it once, but no idea how to make it appear.

**Comment by PredatH0r** [comment]
That dialog is only shown as part of the "migration" when the master server setting in the .ini file is configured to "<Steam Web API>".
At the time I made those changes I wasn't sure if Steam/Valve is willing to issue steam api keys to individual players, or if they only want to issue them to web site operators and developers (since you need to specifiy a domain name where the key is going to be used).
