### ISSUE TITLE
Error requesting server list from master server: Timeout

### ISSUE THREAD

**Issue by orion486** [PredatH0r/SteamServerBrowser#37]
The program was working fine. Then it starts throwing this message every time when hitting F4 (requesting new server list from steam master server). Previously, I could override this problem by changing my *master server* address from `hl2master.steampowered.com:27011` to `<Steam Web API>`, which required getting an API key from Steam; I, however, lost this key and can't make a new one due to personal reasons; my only alternative is  to use direct addresses. But for some reason `hl2master.steampowered.com:27011` keeps throwing the `Error requesting server list from master server: Timeout` error.

Nothing at all changed on my system since the time it was working fine to when it stopped working (no windows update, no new firewall/connection settings. I am not sure what the cause may be.

I tried deleting the entire folder where the exe is and reinstalling from scratch, the problem persists. Are there any registry keys or other folders storing app settings that I should also delete to ensure a full reinstall?

**Comment by PredatH0r** [comment]
The Steam Web API Key that was previously built into the browswer was disabled by Valvue due to abuse.
People were abusing my browser to stalk players and then start DDoS attacks on servers they are playing on.

Therefore players have to get their own indivudual API keys now, allowing valve to enforce their ToS.

I did not change anything about the legacy master server queries via hl2master.steampowered.com. It seems like Valve shut down the servers. This may be unintentional (as it happened in the past a few times) or deliberate to prevent above mentioned abuse.

**Comment by orion486** [comment]
Ah I see, it's good to know it is not a problem on my end at least. At least I still have the addresses of some of the servers I frequented in my `favorites` list and that list can still be updated using this app; will have to make do for now. Thanks a lot for your reply!

**Comment by PredatH0r** [comment]
I reached out to Valve yesterday, trying to clarify if the master servers are offline by mistake (starting on a Feb 29th) or on purpose. So far I haven't received any response yet.
It's particularly strange since the DNS entry hlmaster resolves to 3 different IPs. The first 2 aren't working, but the 3rd is.

I didn't promote the option to use a personal Web API Key because at the time I made the change, I wasn't sure if that's ok with Valve's ToS. Since the registration process requires to specify a domain name where the key is going to be used, it's targeted at web site operators and not individual players.
And since the hl2master was working at that time, I left that as the default option.

It's all in a limbo atm.

**Comment by orion486** [comment]
That's an interesting finding! It then sounds like a good temp fix for now, as `hl2master.steampowered.com` keeps randomly timing out.

Temp fix when getting the error message `Error requesting server list from master server: Timeout` and without using the `<Steam Web API>` key method: 
1. Go to your router's DNS lookup page or to an online DNS lookup service like [https://ping.eu/nslookup/](https://ping.eu/nslookup/).
2. Enter the URL `hl2master.steampowered.com` and take note of the list of IP's that it returns.
3. In the `SteamServerBrowser` application, find the `Master server` combo box and enter one of the IP's from the previous step (don't forget to append the port number to every IP, it can be either `27011` or `27015`).
4. Repeat the previous step for each IP until you find one that works.

Valve says in their dev page [here](https://developer.valvesoftware.com/wiki/Master_Server_Query_Protocol#Master_servers) that the domain `hl2master.steampowered.com:27011` indeed points to 3 IP's and that these may or may not change:
```
hl2master.steampowered.com:27011 (numeric IP may change)
This domain name points to 3 A records (IPs), one of them using a different port (27015) according to the MasterServer2.vdf.
```

The above temp fix could be implemented to have the app automatically run through each of the IP's to find one that doesn't time out and which will returns a valid game-server list.

**Comment by PredatH0r** [comment]
I was able to contact someone at Valve who looked into the issue and was able to fix it.
The DNS now returns the new IPs of the servers after they were migrated.

**Comment by Neoony** [comment]
Same thing happening now
I have a sourcemod plugin checking the hl2 master server, stopped working few days ago.
Tried powershell script, direct ips from what the hl2master.steampowered.com DNS returns or with dns, timeouts
Tried SteamServerBrowser, also timeout

They had a ddos attack a while ago, but I think it worked the weekend after that

> I was able to contact someone at Valve who looked into the issue and was able to fix it. The DNS now returns the new IPs of the servers after they were migrated.

Did you just make a ticket the last time? Or do you have some better contact?
EDIT: anyways, logged a HL2 ticket and I will see

**Comment by orion486** [comment]
Yep, getting `Error requesting server list from master server: Timeout` again since a week or two ago. It looks like the master IP's need to be updated once again by Steam.

Getting the current IP's using Google's DNS:
```
$ nslookup hl2master.steampowered.com 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 dns.google

Name:      hl2master.steampowered.com
Address 1: 208.64.200.65 208-64-200-65.steampowered.com
Address 2: 208.78.164.210 164-78-208-210.valve.net
Address 3: 192.69.99.29 192-69-99-29.valve.net
```
Querying each IP on ports `27011` and `27015`:
```
$ curl -L --connect-timeout 5 "192.69.99.29:{27011,27015}" "208.64.200.65:{27011,27015}" "208.78.164.210:{27011,27015}"

[1/2]: 192.69.99.29:27011 --> <stdout>
--_curl_--192.69.99.29:27011
curl: (28) Connection timed out after 5000 milliseconds

[2/2]: 192.69.99.29:27015 --> <stdout>
--_curl_--192.69.99.29:27015
curl: (28) Connection timed out after 5000 milliseconds

[1/2]: 208.64.200.65:27011 --> <stdout>
--_curl_--208.64.200.65:27011
curl: (28) Connection timed out after 5000 milliseconds

[2/2]: 208.64.200.65:27015 --> <stdout>
--_curl_--208.64.200.65:27015
curl: (28) Connection timed out after 5000 milliseconds

[1/2]: 208.78.164.210:27011 --> <stdout>
--_curl_--208.78.164.210:27011
curl: (28) Connection timed out after 5000 milliseconds

[2/2]: 208.78.164.210:27015 --> <stdout>
--_curl_--208.78.164.210:27015
curl: (28) Connection timed out after 5000 milliseconds

```

**Comment by PredatH0r** [comment]
Sorry for my late reply and thanks for the detailed info.
I reached out to my contact from last year just now and hope we can get an update whether this is due to a technical issue or a discontinuation of the UDP master server query service.

**Comment by Neoony** [comment]
Just to mention
I had a personal hl2 ticket logged to steam, but basically just "steam support cant check your connection, check your connection, links to steam connection issues guides, post on forums maybe someone can help you with your issue"
Logged a steamworks ticket (Empires mod, steam API category) to hopefully reach someone technical, but still no response since 19 October
So no luck here so far

**Comment by PredatH0r** [comment]
I haven't received a response from my former contact at Valve, so no luck here either.

**Comment by Neoony** [comment]
Seems hl2master.steampowered.com now no longer even resolves into IPs
Just completely down
I guess thats one answer

( hl2master.steampowered.com points to hl2master.discovery.steamserver.net which has no records )
