### ISSUE TITLE
columns not restored on restart

### ISSUE THREAD

**Issue by atomGit** [PredatH0r/SteamServerBrowser#8]
v1.12.2
upon restarting, the columns are restored to their default state

**Comment by PredatH0r** [comment]
I'm not storing the column state because it is a lot more complicated that it sounds.
Columns are changed dynamically depending on which game you select. e.g. Toxikk, Reflex, Quake Live Testing, CS:GO show different columns. This means I'd have to store it on a per-game basis.
But then you'd have to resize and/or reorder the columns for every game, which also sucks.
When I add new columns an a new version, they would become invisible when I restore your column state which doesn't contain those new columns.... and I wouldn't know where to place them if you reorder everything.

**Comment by atomGit** [comment]
could this be implemented in a more rudimentary way perhaps?
for example, just save the last used column names, order (and optionally widths) and restore it upon restart - if the user changes games, then reset to default (honestly though, i can't possibly imagine anyone ever changing to anything other than CS:GO LOL!)

**Comment by PredatH0r** [comment]
added option "Remember column layout for each tab" in v2.0
layout is restored at program start and when switching between tabs
